### ISSUE TITLE
error signal in lower right hand corner

### ISSUE THREAD

**Issue by sarahjcamm** [Alb-310/Geogramint#29] opened 2024-05-12 19:29 UTC
Hello - 

Apologies if there is an obvious fix - I have zero programming experience and have used Google to figure out how to work this thing. Now, I have finally got it running, but when I press start search, I get this pesky little error image pop up (a red exclamation point) in the lower right hand corner. Please advise! Thank you!

**Comment by Alb-310** [comment] 2024-08-03 22:28
Hello, sorry for the late reply, this is a Geogramint error, it can be related to many things. I will need some logs to be able to help you. 
It can be caused by :
- wrong settings in account's Privacy and Security settings
![image](https://github.com/user-attachments/assets/81c92239-06c5-4025-9f9b-31e15ad3c843)
- invalid api key
- Permission Error due to the place where Geogramint is installed on your pc ( it can be fixed by installing Geogramint in a place where it doesn't need Administrator permissions like for example in a folder on your Desktop )
- No telegram users or groups detected in the area

**Comment by sarahjcamm** [comment] 2024-08-06 09:03
Thanks for getting back to me!

Ah, well it sounds like that's the issue. Does Geogramint not work on a Mac
computer?

(I am a beginner/ not very technical, so please bear with me).

Best,
Sarah

**Comment by Alb-310** [comment] 2024-08-06 09:18
Hello, no problem, yes Geogramint works on Mac. When you run it, beside the user interface you should have a windows with technical logs produced by the tool.
If you can retry and send me the logs that appears when you are getting the error I can help you find the solution

**Closed as completed** 2024-08-29 17:00 UTC
Labels: no answers
